spring:
  application:
    name: Payment Server - Prod

  datasource:
    url: jdbc:postgresql://:5432/default_db

app:
  telegram:
    societyId: -1002246042299
    societyLink: https://t.me/+oSjq-iHU_k5iMGQy
    ownerId: 438139618

server:
  error:
    whitelabel:
      enabled: false
    include-stacktrace: never

logging:
  level:
    org:
      springframework:
        security: WARN