spring:
  application:
    name: Payment Server - Prod

app:
  publicKey: pk_885fd2d2190460531c2c9a1fc4676

  telegram:
    botToken: 2200734999:AAEBOJ8hC8Ppoope_R2X-M7dSfl4L_UEfAM
    authExpirationTime: 300

server:
  error:
    whitelabel:
      enabled: false
    include-stacktrace: never

logging:
  level:
    org:
      springframework:
        security: WARN