spring:
  application:
    name: ${app.name} - ${app.version} - ${app.bugsnag.release-stage}

  datasource:
    url: jdbc:postgresql://${DB_IP}:5432/${DB_NAME}
    username: ${PG_LOGIN}
    password: ${PG_PASSWORD}
    driver-class-name: org.postgresql.Driver

  thymeleaf:
    cache: false
    prefix: file:src/main/resources/templates/

  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: validate

  threads:
    virtual:
      enabled: true

server:
  forward-headers-strategy:
    framework
  servlet:
    context-path: /
  error:
    path: /error

app:
  version: "@project.version@"
  name: "@project.name@"

  cloudpayments:
    public-key: ${PK_ID}
    password: ${PK_PASSWORD}

  telegram:
    bot-token: ${BOT_TOKEN}
    society-id: -5084801418
    auth-expiration-time: 300
    society-link: https://t.me/+rS92AF6gRrJmYzIy
    ownerId: 5000568454

  bugsnag:
    api-key: c732c7f9ec9a0c3c34f170197f40a6b7
    release-stage: development