spring:
  datasource:
    url: jdbc:postgresql://${DB_IP}:5432/${DB_NAME}

app:
  telegram:
    society-id: -1002246042299
    society-link: https://t.me/+oSjq-iHU_k5iMGQy
    ownerId: 438139618

  bugsnag:
    release-stage: production

server:
  error:
    whitelabel:
      enabled: false
    include-stacktrace: never