spring:
  application:
    name: Payment Server - 0.3.1 - DEV

  datasource:
    url: jdbc:postgresql://${DB_IP}:5432/${DB_NAME}
    username: ${PG_LOGIN}
    password: ${PG_PASSWORD}
    driver-class-name: org.postgresql.Driver

  thymeleaf:
    cache: false
    prefix: file:src/main/resources/templates/

  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: validate

  threads:
    virtual:
      enabled: true

server:
  servlet:
    context-path: /
  error:
    path: /error

app:
  cloudpayments:
    publicKey: ${PK_ID}
    password: ${PK_PASSWORD}

  telegram:
    botToken: ${BOT_TOKEN}
    societyId: -5084801418
    authExpirationTime: 300
    societyLink: https://t.me/+rS92AF6gRrJmYzIy
    ownerId: 5000568454

logging:
  level:
    org:
      springframework:
        security: DEBUG